### ISSUE TITLE
Unable to find generator

### ISSUE THREAD

**Issue by MrThursday** [bizcasfri/generator-webapi-owin-jwt-aspnet-identity#1]
Hi,

Following the instructions to get this project up and running via yeoman does not seem to work. I am getting an error "You don't seem to have a generator with the name webapi-owin-jwt-aspnet-identity installed."

I heave tried "yo generator-webapi-owin-jwt-aspnet-identity" with the same results.

I can confirm I can see the generator in node_modules\generator-webapi-owin-jwt-aspnet-identity.

![capture](https://cloud.githubusercontent.com/assets/5286116/9428650/a5e7ab04-49b5-11e5-9cdf-7f860c24f6f2.PNG)

**Comment by bizcasfri** [comment]
When using yo leave the word "generator" off the package name.
yo webapi-owin-jwt-aspnet-identity

Thanks!

Sent using CloudMagic [https://cloudmagic.com/k/d/mailapp?ct=pi&cv=6.4.21&pv=8.3]
On Sun, Aug 23, 2015 at 9:41 AM,
bizcasfri/generator-webapi-owin-jwt-aspnet-identity
<reply@reply.github.com>
wrote:
Hi,

Following the instructions to get this project up and running via yeoman does
not seem to work. I am getting an error "You don't seem to have a generator with
the name webapi-owin-jwt-aspnet-identity installed."

I heave tried "yo generator-webapi-owin-jwt-aspnet-identity" with the same
results.

I can confirm I can see the generator in
node_modules\generator-webapi-owin-jwt-aspnet-identity.

capture
[https://cloud.githubusercontent.com/assets/5286116/9428650/a5e7ab04-49b5-11e5-9cdf-7f860c24f6f2.PNG]
[https://cloud.githubusercontent.com/assets/5286116/9428650/a5e7ab04-49b5-11e5-9cdf-7f860c24f6f2.PNG]

—
Reply to this email directly or view it on GitHub
[https://github.com/bizcasfri/generator-webapi-owin-jwt-aspnet-identity/issues/1] .[https://github.com/notifications/beacon/AByMDT6iMk2l1Wwm8JGkilVTVT4Ez8Glks5oqdMOgaJpZM4Fwl27.gif]

**Comment by oduwole** [comment]
No refresh token capability implemented.
How can this be implemented

**Comment by bizcasfri** [comment]
I am planning on modifying the generator to implement refresh tokens but just haven't had the time.  It will probably be a month or so before I get to it.
